seed: 42
dataset:
  name: cifar10
  root: ./data
  num_classes: 10
data:
  img_size: 32
  batch_size: 128
  num_workers: 4
model:
  name: simple_cnn
  kwargs: {}
optimizer:
  lr: 0.003
  weight_decay: 0.0001
scheduler:
  one_cycle: true
  pct_start: 0.1
  div_factor: 25.0
  final_div_factor: 10000.0
trainer:
  epochs: 20
  device: cuda    # set to 'cpu' if you don't have a GPU
  amp: true       # mixed precision
  early_stopping_patience: 5
  max_grad_norm: 1.0
  checkpoint_dir: checkpoints
  log_dir: logs
  resume: null
